/** mat4array_defs.h */
#ifndef WINDMILL_MAT4ARRAY_DEFS_H_
#define WINDMILL_MAT4ARRAY_DEFS_H_
#define MAT4ARRAY_LEN 16
#define MAT4VEC_LEN 4
enum {
      MAT4ARRAY_U_ERROR
    , MAT4ARRAY_IDENTITY
    , MAT4ARRAY_ZERO
    , MAT4ARRAY_DEBUG
/*  , MAT4ARRAY_MODEL
    , MAT4ARRAY_VIEW
    , MAT4ARRAY_CLIP */
    , MAT4ARRAY_O_ERROR
};
#endif
